version: "3.9"
services:
   db:
      image: postgres:latest

      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=test

      ports:
         - "5555:5432"

      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U postgres"]
         interval: 10s
         timeout: 10s
         retries: 5

   node:
      build:
         context: .
         dockerfile: ./Dockerfile

      environment:
         - POSTGRES_HOST=db
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=test
         - POSTGRES_PORT=5432

      ports:
         - "3001:3000"

      depends_on:
         db:
            condition: service_healthy

      links:
         - db

      restart: always
